---
- name: Install MongoDB 4.4
  hosts: localhost
  become: true
  tasks:
  - name: Wait 1 minute
    wait_for:
      timeout: 60

  - name: Add APT key
    apt_key:
      id: EA312927
      keyserver: keyserver.ubuntu.com

  - name: Add APT repository
    apt_repository:
      repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      state: present

  - name: Install mongodb package
    apt:
      name: mongodb-org
      state: present
      allow_unauthenticated: yes

  - name: Configure service supervisor
    systemd:
      name: mongod
      enabled: yes
