---
- name: Deploy app
  hosts: app
  tags: deploy-tag
  become: true
  tasks:
  - name: Install git
    become: yes
    apt:
      name: git
      state: present

  - name: Fetch the latest version of application code
    git:
      repo: 'https://github.com/express42/reddit.git'
      dest: /home/ubuntu/reddit
      version: monolith

  - name: Bundle install
    bundler:
      state: present
      chdir: /home/ubuntu/reddit
