name: Manual tests for homework

on:
  push:
    branches-ignore: main
  pull_request:
    branches-ignore: main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Run tests
      run: echo "Hello, World!"

    - name: Check terraform stage templates
      run: pwd && ls -l

      #    - name: Check packer templates
      #run: find packer/ ! -name "variables.json" -a ! -name "key.json" -a -name "*.json" -type f -print0 | xargs -0 -n1 packer validate -syntax-only

      #- name: Check terraform stage templates
      #run: cd terraform/stage/ && terraform validate
